/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
/**
 *
 * @author LOG IN
 */
public class userprofile extends javax.swing.JInternalFrame {

    /**
     * Creates new form userprofie
     */
    public userprofile(int u_id, String u_name, String u_email, String u_pass, String u_type) {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        // Display the student information on the labels
        p_name.setText(" " + u_name);
        p_email.setText(" " + u_email);
    }
  Color navcolor = new Color(102,102,102);
    Color headcolor = new Color(102,102,102);
    Color bodycolor = new Color(204,204,204);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p_name = new javax.swing.JLabel();
        p_email = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        mygrades = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        SEMREP = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        majorsubrep = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 10, 190, 170);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("EMAIL:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 90, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FULL NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 150, 50);
        jPanel1.add(p_name);
        p_name.setBounds(110, 20, 190, 30);
        jPanel1.add(p_email);
        p_email.setBounds(70, 80, 180, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 180));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mygrades.setBackground(new java.awt.Color(153, 153, 153));
        mygrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mygradesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mygradesMouseExited(evt);
            }
        });
        mygrades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Appointment");
        mygrades.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 30));

        jPanel6.add(mygrades, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, 150));

        SEMREP.setBackground(new java.awt.Color(153, 153, 153));
        SEMREP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SEMREPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SEMREPMouseExited(evt);
            }
        });
        SEMREP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Reports");
        SEMREP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 140, 20));

        jPanel6.add(SEMREP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 150));

        majorsubrep.setBackground(new java.awt.Color(153, 153, 153));
        majorsubrep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                majorsubrepMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                majorsubrepMouseExited(evt);
            }
        });
        majorsubrep.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Schedule");
        majorsubrep.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 30));

        jPanel6.add(majorsubrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 150));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 700, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mygradesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseEntered
        mygrades.setBackground(bodycolor);
    }//GEN-LAST:event_mygradesMouseEntered

    private void mygradesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mygradesMouseExited
        mygrades.setBackground(navcolor);
    }//GEN-LAST:event_mygradesMouseExited

    private void SEMREPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseEntered
        SEMREP.setBackground(bodycolor);
    }//GEN-LAST:event_SEMREPMouseEntered

    private void SEMREPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SEMREPMouseExited
        SEMREP.setBackground(navcolor);
    }//GEN-LAST:event_SEMREPMouseExited

    private void majorsubrepMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseEntered
        majorsubrep.setBackground(bodycolor);
    }//GEN-LAST:event_majorsubrepMouseEntered

    private void majorsubrepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_majorsubrepMouseExited
        majorsubrep.setBackground(navcolor);
    }//GEN-LAST:event_majorsubrepMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SEMREP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel majorsubrep;
    private javax.swing.JPanel mygrades;
    public javax.swing.JLabel p_email;
    public javax.swing.JLabel p_name;
    // End of variables declaration//GEN-END:variables
}
